/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labapp;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.BorderFactory;

/**
 *
 * @author masihullahomar
 */
public class Laboratorians extends javax.swing.JFrame {

    /**
     * Creates new form Laboratorians
     */
    private Connection connection;
    private Statement stm;
    private ResultSet rs;
    private DefaultTableModel model;
    
    public Laboratorians() {
        initComponents();
        setLocationRelativeTo(null); 
//        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
//        this.getContentPane().setBackground(Color.white);
        connection = new DatabaseConnection().connect();
        model = new DefaultTableModel();
        laboratorianTable.setModel(model);  // Set the model for the laboratorian table
        showLaboratorians(); 
    }
    
    private void showLaboratorians() {
        try {
            // Initialize table columns
            model.setColumnCount(0); // Reset the columns before adding new ones
            model.addColumn("Laboratorian ID");
            model.addColumn("Laboratorian Name");
            model.addColumn("Laboratorian Specialization");
            model.addColumn("Laboratorian Contact Info");
            

            // Execute query to fetch laboratorian data
            stm = connection.createStatement();
            rs = stm.executeQuery("SELECT * FROM laboratorians");

            // Clear previous rows
            model.setRowCount(0); // Reset the rows before populating them

            // Populate the table with data from the result set
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("laboratorianId"),
                    rs.getString("laboratorianName"),
                    rs.getString("specialization"),
                    rs.getString("contactInfo")
                    
                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    
     private void clearLaboratorianFields() {
        laboratorianIdField.setText("");
        laboratorianNameField.setText("");
        laboratorianContactInfoField.setText("");
        laboratorianSpecializationField.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laboratorianIdField = new javax.swing.JTextField();
        deleteLaboratorianBtn = new RoundedButton(20);
        jLabel4 = new javax.swing.JLabel();
        addLaboratorianBtn = new RoundedButton(20);
        jScrollPane1 = new javax.swing.JScrollPane();
        laboratorianTable = new javax.swing.JTable();
        laboratorianContactInfoField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        laboratorianNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        laboratorianSpecializationField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        updateLaboratorianBtn = new RoundedButton(20);
        jPanel1 = new RoundedPanel(0,30,0,30);
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 550));

        laboratorianIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorianIdFieldActionPerformed(evt);
            }
        });

        deleteLaboratorianBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        deleteLaboratorianBtn.setForeground(new java.awt.Color(255, 51, 51));
        deleteLaboratorianBtn.setText("Delete ");
        deleteLaboratorianBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLaboratorianBtnMouseClicked(evt);
            }
        });
        deleteLaboratorianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLaboratorianBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Laboratorian ID");

        addLaboratorianBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        addLaboratorianBtn.setForeground(new java.awt.Color(255, 51, 51));
        addLaboratorianBtn.setText("Add Laboratorian");
        addLaboratorianBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLaboratorianBtnMouseClicked(evt);
            }
        });

        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));

        laboratorianTable.setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        laboratorianTable.setAutoCreateRowSorter(true);
        laboratorianTable.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        laboratorianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Laboratorian ID ", "Laboratorian Name", "Laboratorian Specialization", "Laboratorian Contact Info"
            }
        ));
        laboratorianTable.setFocusable(false);
        jScrollPane1.setViewportView(laboratorianTable);

        laboratorianContactInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorianContactInfoFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Name");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Contact Info");

        laboratorianSpecializationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorianSpecializationFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Specialization");

        updateLaboratorianBtn.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        updateLaboratorianBtn.setForeground(new java.awt.Color(255, 51, 51));
        updateLaboratorianBtn.setText("Update");
        updateLaboratorianBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateLaboratorianBtnMouseClicked(evt);
            }
        });
        updateLaboratorianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLaboratorianBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 25, 25));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/patient_w.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/result_w.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/test_w.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/laboratorian_w.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/log_out.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/lab.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/x-circle.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/minus-circle.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/minimize.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 25, 25));
        jLabel14.setText("Marmara Medical Lab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(laboratorianIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(laboratorianNameField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(laboratorianSpecializationField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(laboratorianContactInfoField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(addLaboratorianBtn)
                                                .addComponent(deleteLaboratorianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(updateLaboratorianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laboratorianIdField)
                            .addComponent(laboratorianNameField))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laboratorianContactInfoField)
                            .addComponent(laboratorianSpecializationField))
                        .addGap(65, 65, 65)
                        .addComponent(addLaboratorianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateLaboratorianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(deleteLaboratorianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laboratorianIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorianIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorianIdFieldActionPerformed

    private void deleteLaboratorianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLaboratorianBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteLaboratorianBtnActionPerformed

    private void laboratorianContactInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorianContactInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorianContactInfoFieldActionPerformed

    private void laboratorianSpecializationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorianSpecializationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorianSpecializationFieldActionPerformed

    private void updateLaboratorianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLaboratorianBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLaboratorianBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new Patients().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new Results().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new Tests().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new Laboratorians().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new DashBoard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(Tests.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void addLaboratorianBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLaboratorianBtnMouseClicked
        // TODO add your handling code here:
        try {
        // Get input from the fields
        String laboratorianId = laboratorianIdField.getText().trim();
        String laboratorianName = laboratorianNameField.getText().trim();
        String laboratorianSpecialization = laboratorianSpecializationField.getText().trim();
        String laboratorianContactInfo = laboratorianContactInfoField.getText().trim();

        // Validate that none of the required fields are empty
        if (laboratorianId.isEmpty() || laboratorianName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields (Laboratorian ID and Name).");
            return;
        }

        // Validate that laboratorianId is a valid integer
        int laboratorianIdInt;
        try {
            laboratorianIdInt = Integer.parseInt(laboratorianId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Laboratorian ID must be a valid integer.");
            return;
        }

        // Prepare the SQL query to insert the data
        String query = "INSERT INTO laboratorians (laboratorianId, laboratorianName, contactInfo, specialization) VALUES (?, ?, ?, ?)";
        PreparedStatement pst = connection.prepareStatement(query);
        pst.setInt(1, laboratorianIdInt); // Set laboratorianId as integer
        pst.setString(2, laboratorianName);
        
        // Handle nullable fields
        if (laboratorianContactInfo.isEmpty()) {
            pst.setNull(3, java.sql.Types.VARCHAR);  // Set null for contactInfo if it's empty
        } else {
            pst.setString(3, laboratorianContactInfo);
        }

        if (laboratorianSpecialization.isEmpty()) {
            pst.setNull(4, java.sql.Types.VARCHAR);  // Set null for specialization if it's empty
        } else {
            pst.setString(4, laboratorianSpecialization);
        }

        // Execute the query
        pst.executeUpdate();

        // Show success message and refresh the table
        JOptionPane.showMessageDialog(this, "Laboratorian added successfully.");
        showLaboratorians(); // Refresh the table with updated data
        clearLaboratorianFields(); // Clear input fields after adding
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_addLaboratorianBtnMouseClicked

    private void deleteLaboratorianBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLaboratorianBtnMouseClicked
        // TODO add your handling code here:
        try {
        int selectedRow = laboratorianTable.getSelectedRow();
        if (selectedRow != -1) {
            String laboratorianId = model.getValueAt(selectedRow, 0).toString(); // Get laboratorianId from the selected row

            // Start a transaction to ensure data consistency
            connection.setAutoCommit(false);

            // Delete dependent rows from resultsTbl
            String deleteResultsQuery = "DELETE FROM resultsTbl WHERE laboratorianId = ?";
            PreparedStatement pstResults = connection.prepareStatement(deleteResultsQuery);
            pstResults.setString(1, laboratorianId);
            pstResults.executeUpdate();

            // Delete the laboratorian from laboratorians table
            String deleteLaboratorianQuery = "DELETE FROM laboratorians WHERE laboratorianId = ?";
            PreparedStatement pstLaboratorian = connection.prepareStatement(deleteLaboratorianQuery);
            pstLaboratorian.setString(1, laboratorianId);
            pstLaboratorian.executeUpdate();

            // Commit the transaction
            connection.commit();

            // Remove the row from the table model
            model.removeRow(selectedRow);

            JOptionPane.showMessageDialog(this, "Laboratorian and related results deleted successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Please select a laboratorian to delete.");
        }
    } catch (SQLException ex) {
        try {
            // Rollback the transaction in case of an error
            connection.rollback();
        } catch (SQLException rollbackEx) {
            JOptionPane.showMessageDialog(this, "Rollback Error: " + rollbackEx.getMessage());
        }
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    } finally {
        try {
            // Reset auto-commit to true
            connection.setAutoCommit(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error resetting auto-commit: " + ex.getMessage());
        }
    }

    }//GEN-LAST:event_deleteLaboratorianBtnMouseClicked

    private void updateLaboratorianBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateLaboratorianBtnMouseClicked
        // TODO add your handling code here:
        try {
        int selectedRow = laboratorianTable.getSelectedRow();
        if (selectedRow != -1) {
            String laboratorianId = model.getValueAt(selectedRow, 0).toString(); // Get laboratorianId from the selected row
            String laboratorianName = laboratorianNameField.getText();
            String laboratorianContactInfo = laboratorianContactInfoField.getText();
            String laboratorianSpecialization = laboratorianSpecializationField.getText();

            // Prepare the SQL query to update the laboratorian record
            String query = "UPDATE laboratorianTbl SET laboratorianName = ?, laboratorianContactInfo = ?, laboratorianSpecialization = ? WHERE laboratorianId = ?";
            PreparedStatement pst = connection.prepareStatement(query);
            pst.setString(1, laboratorianName);
            pst.setString(2, laboratorianContactInfo);
            pst.setString(3, laboratorianSpecialization);
            pst.setString(4, laboratorianId);

            // Execute the update
            pst.executeUpdate();
            
            // Refresh the table
            JOptionPane.showMessageDialog(this, "Laboratorian updated successfully.");
            showLaboratorians();
            clearLaboratorianFields(); // Clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "Please select a laboratorian to update.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_updateLaboratorianBtnMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        if(this.getExtendedState()!=Tests.MAXIMIZED_BOTH){
            this.setExtendedState(Tests.MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(Tests.NORMAL);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Laboratorians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Laboratorians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Laboratorians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Laboratorians.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Laboratorians().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLaboratorianBtn;
    private javax.swing.JButton deleteLaboratorianBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField laboratorianContactInfoField;
    private javax.swing.JTextField laboratorianIdField;
    private javax.swing.JTextField laboratorianNameField;
    private javax.swing.JTextField laboratorianSpecializationField;
    private javax.swing.JTable laboratorianTable;
    private javax.swing.JButton updateLaboratorianBtn;
    // End of variables declaration//GEN-END:variables

}
