/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import java.awt.Color;
import java.sql.*;
import java.util.Date;  // For handling dates in Java

//import java.awt.event.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import javax.swing.table.DefaultTableModel;
import javax.swing.BorderFactory;

/**
 *
 * @author masihullahomar
 */
public class Patients extends javax.swing.JFrame {

    /**
     * Creates new form Patients
     */
    private Connection connection;
    private Statement stm;
    private ResultSet rs;
    private DefaultTableModel model;
    
    public Patients() {
        initComponents();
        setLocationRelativeTo(null);
//        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),20,20));
//        getContentPane().setBackground(Color.white);
//        connection = new DatabaseConnection().connect();
        model = new DefaultTableModel();
        patientTable.setModel(model);
        showPatients();
    }
    
    private void showPatients() {
    try {

        // Initialize table model
        model.setColumnCount(0);
        model.addColumn("Patient ID");
        model.addColumn("Name");
        model.addColumn("Phone");
        model.addColumn("Address");
        model.addColumn("Gender");
        model.addColumn("Date of Birth");
//        patientTable.setModel(model);

        // Query to select all patients
        stm = connection.createStatement();
        rs = stm.executeQuery("SELECT * FROM patientTbl");
        
        model.setRowCount(0);

        // Populate table with data from the result set
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("patientId"),
                rs.getString("patientName"),
                rs.getString("patientPhone"),
                rs.getString("patientAddress"),
                rs.getString("gender"),
                rs.getDate("dateOfBirth")
            });
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
}
    
private void clearInputFields() {
    patientIdField.setText("");
    patientNameField.setText("");
    patientPhoneField.setText("");
    patientAddressField.setText("");
    genderField.setSelectedIndex(0); // Resets the gender dropdown to the first item
    patientDateOfBirthField.setDate(null); // Clears the date of birth field
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientDateOfBirthField = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        patientIdField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        patientNameField = new javax.swing.JTextField();
        genderField = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        patientPhoneField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        patientAddressField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(patientDateOfBirthField);
        patientDateOfBirthField.setBounds(110, 310, 140, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 70, 130, 0);
        getContentPane().add(patientIdField);
        patientIdField.setBounds(110, 100, 120, 23);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Patient Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 70, 130, 16);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Patient Date Of Birth");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 280, 140, 16);

        patientNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(patientNameField);
        patientNameField.setBounds(250, 100, 120, 23);

        genderField.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        genderField.setForeground(new java.awt.Color(153, 153, 153));
        genderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", " " }));
        genderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderField);
        genderField.setBounds(110, 160, 100, 20);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Patient Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 70, 140, 16);
        getContentPane().add(patientPhoneField);
        patientPhoneField.setBounds(250, 160, 120, 23);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("Patient Gender");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(110, 140, 140, 16);

        patientAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientAddressFieldActionPerformed(evt);
            }
        });
        getContentPane().add(patientAddressField);
        patientAddressField.setBounds(110, 240, 260, 23);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Patient Address");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 210, 140, 16);

        //jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));

        patientTable.setAutoCreateRowSorter(true);
        patientTable.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Number ", "Name", "Gender", "Address", "Phone", "Date Of Birth"
            }
        ));
        patientTable.setGridColor(java.awt.Color.white);
        jScrollPane1.setViewportView(patientTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 70, 560, 370);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/x-circle.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1050, 20, 25, 25);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/minus-circle.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16);
        jLabel16.setBounds(990, 20, 25, 25);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labapp/Statics/minimize.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1020, 20, 25, 25);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 3, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 25, 25));
        jLabel14.setText("Marmara Medical Lab");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(640, 10, 161, 19);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("Patient Phone");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(250, 140, 140, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameFieldActionPerformed

    private void genderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFieldActionPerformed

    private void patientAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientAddressFieldActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
//        this.setExtendedState(Tests.ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
//        if(this.getExtendedState()!=Tests.MAXIMIZED_BOTH){
//            this.setExtendedState(Tests.MAXIMIZED_BOTH);
//        }else{
//            this.setExtendedState(Tests.NORMAL);
//        }
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Patients().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> genderField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientAddressField;
    private com.toedter.calendar.JDateChooser patientDateOfBirthField;
    private javax.swing.JTextField patientIdField;
    private javax.swing.JTextField patientNameField;
    private javax.swing.JTextField patientPhoneField;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables

}
